# set the baseURL for CI verification
baseURL = "/"
title = "CommunityOverCode Asia 2024"
theme = "apachecon"
# When enabled, creates URL of the form /filename.html instead of /filename/.
uglyURLs = true
#hasCJKLanguage = true
enableRobotsTXT = true

languageCode = "en-us"
DefaultContentLanguage = "en"



[params]
  author = "ALC-Beijing"
  description = "Welcome to CommunityOverCode (ApacheCon Asia) 2024"
  keywords = ["CommunityOverCode","CommunityOverCodeAsia","ApacheConAsia2024"]
  schedule = ["2024-07-26", "2024-07-27", "2024-07-28"]

[languages.en]
languageName = "English"
weight = 1

[languages.zh]
languageName = "中文"
weight = 2

disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe = true

# menu for en (final list includes translated pages from /content)
[[languages.en.menu.main]]
name = "Guide"
url = "/guide/visa_letter_request.html"
weight = 1

[[languages.en.menu.main]]
name = "Venue + Travel"
url = "/venue_travel/venue.html"
weight = 2


# menu for ZH language (final list includes translated pages from /content)
[[languages.zh.menu.main]]
name = "参会指南"
url = "/zh/guide/visa_letter_request.html"
weight = 1

[[languages.zh.menu.main]]
name = "会场 + 旅行"
url = "/zh/venue_travel/venue.html"
weight = 2
